# fly.toml app configuration file generated for atb-web on 2023-08-17T19:17:41-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "atb-web"
primary_region = "sea"

[build]
  image = "ghcr.io/arunscape/aruns-treasury-branches/atb-web:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
