version: "3"
services:
  questdb:
    container_name: questdb
    image: questdb/questdb
    ports:
      - 9000:9000 # webui and rest api
      - 9009:9009 # influxdb line protocol
      - 8812:8812 # postgres wire protocol
      - 9003:9003 # min health server
    environment:
      POSTGRES_PASSWORD: changeme
    volumes:
      - ./questdb:/root/.questdb/