import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3.3/samples
 * This project uses @Incubating APIs which are subject to change.
 */
repositories {
    mavenCentral()
}

plugins {
//     kotlin
     java
     id("idea")
     id("org.jetbrains.kotlin.jvm") version "latest.release"
     id("com.github.johnrengelman.shadow") version "latest.release"
}

group "xyz.woosaree.minecraft"
version = "1.0-SNAPSHOT"



dependencies {
//    compile("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
}

//tasks.withType<KotlinCompile> {
//    kotlinOptions {
//        jvmTarget = "1.8"
//        freeCompilerArgs = listOf("-Xjsr305=strict")
//    }
//}

//sourceCompatibility = 1.8
//targetCompatibility = 1.8

//idea {
//    module {
//        downloadJavadoc = true
//        downloadSources = true
//    }
//}

//compileKotlin {
//    kotlinOptions.jvmTarget = "1.8"
//}
//compileTestKotlin {
//    kotlinOptions.jvmTarget = "1.8"
//}


