[package]
name = "atb_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#redis = { version = "*", features = ["async-std-tls-comp", "cluster", "json"] }
#redis = { git = "https://github.com/redis-rs/redis-rs.git", features = ["async-std-tls-comp", "cluster", "json"] }
tide = "*"
async-std = { version = "*", features = ["attributes"] }
serde = { version = "*", features = ["derive"] }
futures = "*"
#async-graphql = { version = "*", features = ["bson", "chrono"] }
dotenvy = "*"
lazy_static = "*"
#once_cell = "*"
regex = "*"
jsonwebtoken = "*"
base64 = "*"
dotenv_codegen = "*"
#async-graphql-tide = { version = "*", features = ["tide-websockets"] }
#juniper = "*"
tide-acme = "*"
tide-rustls = "*"
chrono = "*"
cookie = "*"
sqlx = { version = "*", features = [ "runtime-async-std-native-tls", "postgres", "macros", "chrono", "uuid"] }
atb_types = { version = "*", path = "../atb_types" }
uuid = { version = "*", features = ["serde"] }
http-types = "*"


[profile.dev.package.sqlx-macros]
opt-level = 3
