kotlin.code.style=official
maven_group=gg.arun
mod_version=1.0-SNAPSHOT
archives_base_name=atb

org.gradle.parallel=true

minecraft_version=1.21.3
yarn_mappings=1.21.3+build.2
loader_version=0.16.7

# Fabric API
fabric_version=0.106.1+1.21.3
kotlin_loader_version=1.12.3+kotlin.2.0.21

#https://fabricmc.net/develop/
#gradlew migrateMappings --mappings "1.21.3+build.2"