[unstable]
[target.'cfg(target_arch = "wasm32")']
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]

[build]
[target.'cfg(not(target_arch = "wasm32"))']
target = "x86_64-unknown-linux-gnu"
rustflags = ["--cfg=sqlx_macros_unstable", "--cfg=has_std"]
