[unstable]

#[target.'cfg(target_arch = "wasm32")']
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]

[build]
target = "x86_64-unknown-linux-gnu"
rustflags = ["-C", "panic=abort"]
