name: Aruns-Treasury-Branches
version: '${project.version}'
main: xyz.woosaree.arunstreasurybranches.ATB
api-version: 1.18
commands:
  atb:
    description: Arun's Treasury branches
    usage: /<command> [args]