[package]
name = "atb_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "*", features = [ "runtime-tokio", "tls-rustls" , "postgres", "macros", "chrono", "uuid"], optional = true }
uuid = { version = "*", features = ["serde"] }
chrono = {version = "*", features = ["serde"]}
serde = { version = "*", features = ["derive"] }
async-trait = "*"
anyhow = "*"

[features]
ssr = [
  "dep:sqlx",
]
