# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and test plugin

on:
  push:
    paths:
      - 'mc-plugin/**'
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
          mvn -B package --file mc-plugin/pom.xml
          ls mc-plugin/target/*.jar
          
    - uses: actions/upload-artifact@v3
      with:
        name: publish plugin
        path: mc-plugin/target/atb-*.jar
        if-no-files-found: error
  
    
